// Generated by `npm run samples` from scripts/sample-data.ts. Do not edit by hand.
// Cached extraction results for the synthetic sample PDFs, keyed by SHA-256. They are what a correct
// extraction returns, built from the sample data (not recorded from the API), and are shown as "cached".
export const sampleExtractions: Record<string, { documentType: string; sample: string; fields: { key: string; value: string; page: number; quote: string }[] }> = {
  "ed56bdafcd08bcd638870e4d5af45c4c3894f27e290f77e108fef314c3494580": {
    "documentType": "modelo_303",
    "sample": "modelo-303_2025_1T.pdf",
    "fields": [
      {
        "key": "fiscal_year",
        "value": "2025",
        "page": 1,
        "quote": "Ejercicio 2025 · Periodo 1T"
      },
      {
        "key": "quarter",
        "value": "1",
        "page": 1,
        "quote": "Ejercicio 2025 · Periodo 1T"
      },
      {
        "key": "nif",
        "value": "B00000000",
        "page": 1,
        "quote": "NIF: B00000000"
      },
      {
        "key": "base_4",
        "value": "0.00",
        "page": 1,
        "quote": "[01] Base imponible al 4 % 0,00"
      },
      {
        "key": "cuota_4",
        "value": "0.00",
        "page": 1,
        "quote": "[03] Cuota al 4 % 0,00"
      },
      {
        "key": "base_10",
        "value": "0.00",
        "page": 1,
        "quote": "[04] Base imponible al 10 % 0,00"
      },
      {
        "key": "cuota_10",
        "value": "0.00",
        "page": 1,
        "quote": "[06] Cuota al 10 % 0,00"
      },
      {
        "key": "base_21",
        "value": "280000.00",
        "page": 1,
        "quote": "[07] Base imponible al 21 % 280.000,00"
      },
      {
        "key": "cuota_21",
        "value": "58800.00",
        "page": 1,
        "quote": "[09] Cuota al 21 % 58.800,00"
      },
      {
        "key": "total_devengado",
        "value": "58800.00",
        "page": 1,
        "quote": "[27] Total cuota devengada 58.800,00"
      },
      {
        "key": "base_deducible_corrientes",
        "value": "190000.00",
        "page": 1,
        "quote": "[28] Cuotas soportadas en operaciones interiores corrientes — base 190.000,00"
      },
      {
        "key": "cuota_deducible_corrientes",
        "value": "39900.00",
        "page": 1,
        "quote": "[29] Cuotas soportadas en operaciones interiores corrientes — cuota 39.900,00"
      },
      {
        "key": "total_deducir",
        "value": "39900.00",
        "page": 1,
        "quote": "[45] Total a deducir 39.900,00"
      },
      {
        "key": "resultado_regimen_general",
        "value": "18900.00",
        "page": 1,
        "quote": "[46] Resultado régimen general 18.900,00"
      },
      {
        "key": "resultado_liquidacion",
        "value": "18900.00",
        "page": 1,
        "quote": "[71] Resultado de la liquidación 18.900,00"
      }
    ]
  },
  "2ade300cde1cf4451791f26d261f651e1c59db8f5bd61373f715bb67283f0e78": {
    "documentType": "modelo_303",
    "sample": "modelo-303_2025_2T.pdf",
    "fields": [
      {
        "key": "fiscal_year",
        "value": "2025",
        "page": 1,
        "quote": "Ejercicio 2025 · Periodo 2T"
      },
      {
        "key": "quarter",
        "value": "2",
        "page": 1,
        "quote": "Ejercicio 2025 · Periodo 2T"
      },
      {
        "key": "nif",
        "value": "B00000000",
        "page": 1,
        "quote": "NIF: B00000000"
      },
      {
        "key": "base_4",
        "value": "0.00",
        "page": 1,
        "quote": "[01] Base imponible al 4 % 0,00"
      },
      {
        "key": "cuota_4",
        "value": "0.00",
        "page": 1,
        "quote": "[03] Cuota al 4 % 0,00"
      },
      {
        "key": "base_10",
        "value": "12000.00",
        "page": 1,
        "quote": "[04] Base imponible al 10 % 12.000,00"
      },
      {
        "key": "cuota_10",
        "value": "1200.00",
        "page": 1,
        "quote": "[06] Cuota al 10 % 1.200,00"
      },
      {
        "key": "base_21",
        "value": "310000.00",
        "page": 1,
        "quote": "[07] Base imponible al 21 % 310.000,00"
      },
      {
        "key": "cuota_21",
        "value": "65100.00",
        "page": 1,
        "quote": "[09] Cuota al 21 % 65.100,00"
      },
      {
        "key": "total_devengado",
        "value": "66300.00",
        "page": 1,
        "quote": "[27] Total cuota devengada 66.300,00"
      },
      {
        "key": "base_deducible_corrientes",
        "value": "214500.00",
        "page": 1,
        "quote": "[28] Cuotas soportadas en operaciones interiores corrientes — base 214.500,00"
      },
      {
        "key": "cuota_deducible_corrientes",
        "value": "45045.00",
        "page": 1,
        "quote": "[29] Cuotas soportadas en operaciones interiores corrientes — cuota 45.045,00"
      },
      {
        "key": "total_deducir",
        "value": "45045.00",
        "page": 1,
        "quote": "[45] Total a deducir 45.045,00"
      },
      {
        "key": "resultado_regimen_general",
        "value": "21255.00",
        "page": 1,
        "quote": "[46] Resultado régimen general 21.255,00"
      },
      {
        "key": "resultado_liquidacion",
        "value": "21255.00",
        "page": 1,
        "quote": "[71] Resultado de la liquidación 21.255,00"
      }
    ]
  },
  "dea5f83db07488a8305611585d9d94f448758896190c451e7274a913c1dc75b2": {
    "documentType": "modelo_303",
    "sample": "modelo-303_2025_3T.pdf",
    "fields": [
      {
        "key": "fiscal_year",
        "value": "2025",
        "page": 1,
        "quote": "Ejercicio 2025 · Periodo 3T"
      },
      {
        "key": "quarter",
        "value": "3",
        "page": 1,
        "quote": "Ejercicio 2025 · Periodo 3T"
      },
      {
        "key": "nif",
        "value": "B00000000",
        "page": 1,
        "quote": "NIF: B00000000"
      },
      {
        "key": "base_4",
        "value": "0.00",
        "page": 1,
        "quote": "[01] Base imponible al 4 % 0,00"
      },
      {
        "key": "cuota_4",
        "value": "0.00",
        "page": 1,
        "quote": "[03] Cuota al 4 % 0,00"
      },
      {
        "key": "base_10",
        "value": "0.00",
        "page": 1,
        "quote": "[04] Base imponible al 10 % 0,00"
      },
      {
        "key": "cuota_10",
        "value": "0.00",
        "page": 1,
        "quote": "[06] Cuota al 10 % 0,00"
      },
      {
        "key": "base_21",
        "value": "265000.00",
        "page": 1,
        "quote": "[07] Base imponible al 21 % 265.000,00"
      },
      {
        "key": "cuota_21",
        "value": "55650.00",
        "page": 1,
        "quote": "[09] Cuota al 21 % 55.650,00"
      },
      {
        "key": "total_devengado",
        "value": "55650.00",
        "page": 1,
        "quote": "[27] Total cuota devengada 55.650,00"
      },
      {
        "key": "base_deducible_corrientes",
        "value": "181200.00",
        "page": 1,
        "quote": "[28] Cuotas soportadas en operaciones interiores corrientes — base 181.200,00"
      },
      {
        "key": "cuota_deducible_corrientes",
        "value": "38052.00",
        "page": 1,
        "quote": "[29] Cuotas soportadas en operaciones interiores corrientes — cuota 38.052,00"
      },
      {
        "key": "total_deducir",
        "value": "38052.00",
        "page": 1,
        "quote": "[45] Total a deducir 38.052,00"
      },
      {
        "key": "resultado_regimen_general",
        "value": "17598.00",
        "page": 1,
        "quote": "[46] Resultado régimen general 17.598,00"
      },
      {
        "key": "resultado_liquidacion",
        "value": "17598.00",
        "page": 1,
        "quote": "[71] Resultado de la liquidación 17.598,00"
      }
    ]
  },
  "4e3e17c147ab1963b4b61e7640184d598c2b085f4078063a4e61b9059b745e56": {
    "documentType": "modelo_303",
    "sample": "modelo-303_2025_4T.pdf",
    "fields": [
      {
        "key": "fiscal_year",
        "value": "2025",
        "page": 1,
        "quote": "Ejercicio 2025 · Periodo 4T"
      },
      {
        "key": "quarter",
        "value": "4",
        "page": 1,
        "quote": "Ejercicio 2025 · Periodo 4T"
      },
      {
        "key": "nif",
        "value": "B00000000",
        "page": 1,
        "quote": "NIF: B00000000"
      },
      {
        "key": "base_4",
        "value": "0.00",
        "page": 1,
        "quote": "[01] Base imponible al 4 % 0,00"
      },
      {
        "key": "cuota_4",
        "value": "0.00",
        "page": 1,
        "quote": "[03] Cuota al 4 % 0,00"
      },
      {
        "key": "base_10",
        "value": "0.00",
        "page": 1,
        "quote": "[04] Base imponible al 10 % 0,00"
      },
      {
        "key": "cuota_10",
        "value": "0.00",
        "page": 1,
        "quote": "[06] Cuota al 10 % 0,00"
      },
      {
        "key": "base_21",
        "value": "335000.00",
        "page": 1,
        "quote": "[07] Base imponible al 21 % 335.000,00"
      },
      {
        "key": "cuota_21",
        "value": "70350.00",
        "page": 1,
        "quote": "[09] Cuota al 21 % 70.350,00"
      },
      {
        "key": "total_devengado",
        "value": "70350.00",
        "page": 1,
        "quote": "[27] Total cuota devengada 70.350,00"
      },
      {
        "key": "base_deducible_corrientes",
        "value": "228300.00",
        "page": 1,
        "quote": "[28] Cuotas soportadas en operaciones interiores corrientes — base 228.300,00"
      },
      {
        "key": "cuota_deducible_corrientes",
        "value": "47943.00",
        "page": 1,
        "quote": "[29] Cuotas soportadas en operaciones interiores corrientes — cuota 47.943,00"
      },
      {
        "key": "total_deducir",
        "value": "47943.00",
        "page": 1,
        "quote": "[45] Total a deducir 47.943,00"
      },
      {
        "key": "resultado_regimen_general",
        "value": "22407.00",
        "page": 1,
        "quote": "[46] Resultado régimen general 22.407,00"
      },
      {
        "key": "resultado_liquidacion",
        "value": "22407.00",
        "page": 1,
        "quote": "[71] Resultado de la liquidación 22.407,00"
      }
    ]
  },
  "0cd2387d14ce5e9db21f432cb762ebb15a125be00b3f2c66b3b33e598d7e85a7": {
    "documentType": "annual_accounts",
    "sample": "cuentas-anuales_2025.pdf",
    "fields": [
      {
        "key": "nif",
        "value": "B00000000",
        "page": 1,
        "quote": "NIF B00000000"
      },
      {
        "key": "fiscal_year",
        "value": "2025",
        "page": 1,
        "quote": "Ejercicio 2025"
      },
      {
        "key": "current_assets",
        "value": "480000.00",
        "page": 1,
        "quote": "B) Activo corriente 480.000,00"
      },
      {
        "key": "cash",
        "value": "120000.00",
        "page": 1,
        "quote": "Efectivo y otros activos líquidos equivalentes 120.000,00"
      },
      {
        "key": "total_assets",
        "value": "830000.00",
        "page": 1,
        "quote": "TOTAL ACTIVO (A + B) 830.000,00"
      },
      {
        "key": "equity",
        "value": "300000.00",
        "page": 1,
        "quote": "A) Patrimonio neto 300.000,00"
      },
      {
        "key": "long_term_bank_debt",
        "value": "250000.00",
        "page": 1,
        "quote": "Deudas con entidades de crédito a largo plazo 250.000,00"
      },
      {
        "key": "current_liabilities",
        "value": "280000.00",
        "page": 1,
        "quote": "C) Pasivo corriente 280.000,00"
      },
      {
        "key": "short_term_bank_debt",
        "value": "60000.00",
        "page": 1,
        "quote": "Deudas con entidades de crédito a corto plazo 60.000,00"
      },
      {
        "key": "revenue",
        "value": "1210000.00",
        "page": 2,
        "quote": "1. Importe neto de la cifra de negocios 1.210.000,00"
      },
      {
        "key": "supplies",
        "value": "-760000.00",
        "page": 2,
        "quote": "4. Aprovisionamientos -760.000,00"
      },
      {
        "key": "depreciation",
        "value": "-35000.00",
        "page": 2,
        "quote": "8. Amortización del inmovilizado -35.000,00"
      },
      {
        "key": "operating_result",
        "value": "115000.00",
        "page": 2,
        "quote": "A) RESULTADO DE EXPLOTACIÓN 115.000,00"
      },
      {
        "key": "financial_expenses",
        "value": "-18000.00",
        "page": 2,
        "quote": "13. Gastos financieros -18.000,00"
      },
      {
        "key": "net_income",
        "value": "72750.00",
        "page": 2,
        "quote": "D) RESULTADO DEL EJERCICIO 72.750,00"
      }
    ]
  }
};
